using Ntmng.Model.Models;

namespace Ntmng.Model.Common;

public static class Countries
{
    public static Country[] GetListOfCountries() => new[]
    {
        new Country { CountryId = 1,Name = "Afghanistan", Code = "AF" },
        new Country { CountryId = 2,Name = "land Islands", Code = "AX" },
        new Country { CountryId = 3,Name = "Albania", Code = "AL" },
        new Country { CountryId = 4,Name = "Algeria", Code = "DZ" },
        new Country { CountryId = 5,Name = "American Samoa", Code = "AS" },
        new Country { CountryId = 6,Name = "AndorrA", Code = "AD" },
        new Country { CountryId = 7,Name = "Angola", Code = "AO" },
        new Country { CountryId = 8,Name = "Anguilla", Code = "AI" },
        new Country { CountryId = 9,Name = "Antarctica", Code = "AQ" },
        new Country { CountryId = 10,Name = "Antigua and Barbuda", Code = "AG" },
        new Country { CountryId = 11,Name = "Argentina", Code = "AR" },
        new Country { CountryId = 12,Name = "Armenia", Code = "AM" },
        new Country { CountryId = 13,Name = "Aruba", Code = "AW" },
        new Country { CountryId = 14,Name = "Australia", Code = "AU" },
        new Country { CountryId = 15,Name = "Austria", Code = "AT" },
        new Country { CountryId = 16,Name = "Azerbaijan", Code = "AZ" },
        new Country { CountryId = 17,Name = "Bahamas", Code = "BS" },
        new Country { CountryId = 18,Name = "Bahrain", Code = "BH" },
        new Country { CountryId = 19,Name = "Bangladesh", Code = "BD" },
        new Country { CountryId = 20,Name = "Barbados", Code = "BB" },
        new Country { CountryId = 21,Name = "Belarus", Code = "BY" },
        new Country { CountryId = 22,Name = "Belgium", Code = "BE" },
        new Country { CountryId = 23,Name = "Belize", Code = "BZ" },
        new Country { CountryId = 24,Name = "Benin", Code = "BJ" },
        new Country { CountryId = 25,Name = "Bermuda", Code = "BM" },
        new Country { CountryId = 26,Name = "Bhutan", Code = "BT" },
        new Country { CountryId = 27,Name = "Bolivia", Code = "BO" },
        new Country { CountryId = 28,Name = "Bosnia and Herzegovina", Code = "BA" },
        new Country { CountryId = 29,Name = "Botswana", Code = "BW" },
        new Country { CountryId = 30,Name = "Bouvet Island", Code = "BV" },
        new Country { CountryId = 31,Name = "Brazil", Code = "BR" },
        new Country { CountryId = 32,Name = "British Indian Ocean Territory", Code = "IO" },
        new Country { CountryId = 33,Name = "Brunei Darussalam", Code = "BN" },
        new Country { CountryId = 34,Name = "Bulgaria", Code = "BG" },
        new Country { CountryId = 35,Name = "Burkina Faso", Code = "BF" },
        new Country { CountryId = 36,Name = "Burundi", Code = "BI" },
        new Country { CountryId = 37,Name = "Cambodia", Code = "KH" },
        new Country { CountryId = 38,Name = "Cameroon", Code = "CM" },
        new Country { CountryId = 39,Name = "Canada", Code = "CA" },
        new Country { CountryId = 40,Name = "Cape Verde", Code = "CV" },
        new Country { CountryId = 41,Name = "Cayman Islands", Code = "KY" },
        new Country { CountryId = 42,Name = "Central African Republic", Code = "CF" },
        new Country { CountryId = 43,Name = "Chad", Code = "TD" },
        new Country { CountryId = 44,Name = "Chile", Code = "CL" },
        new Country { CountryId = 45,Name = "China", Code = "CN" },
        new Country { CountryId = 46,Name = "Christmas Island", Code = "CX" },
        new Country { CountryId = 47,Name = "Cocos (Keeling) Islands", Code = "CC" },
        new Country { CountryId = 48,Name = "Colombia", Code = "CO" },
        new Country { CountryId = 49,Name = "Comoros", Code = "KM" },
        new Country { CountryId = 50,Name = "Congo", Code = "CG" },
        new Country { CountryId = 51,Name = "Congo, The Democratic Republic of the", Code = "CD" },
        new Country { CountryId = 52,Name = "Cook Islands", Code = "CK" },
        new Country { CountryId = 53,Name = "Costa Rica", Code = "CR" },
        new Country { CountryId = 54,Name = "Cote D'Ivoire", Code = "CI" },
        new Country { CountryId = 55,Name = "Croatia", Code = "HR" },
        new Country { CountryId = 56,Name = "Cuba", Code = "CU" },
        new Country { CountryId = 57,Name = "Cyprus", Code = "CY" },
        new Country { CountryId = 58,Name = "Czech Republic", Code = "CZ" },
        new Country { CountryId = 59,Name = "Denmark", Code = "DK" },
        new Country { CountryId = 60,Name = "Djibouti", Code = "DJ" },
        new Country { CountryId = 61,Name = "Dominica", Code = "DM" },
        new Country { CountryId = 62,Name = "Dominican Republic", Code = "DO" },
        new Country { CountryId = 63,Name = "Ecuador", Code = "EC" },
        new Country { CountryId = 64,Name = "Egypt", Code = "EG" },
        new Country { CountryId = 65,Name = "El Salvador", Code = "SV" },
        new Country { CountryId = 66,Name = "Equatorial Guinea", Code = "GQ" },
        new Country { CountryId = 67,Name = "Eritrea", Code = "ER" },
        new Country { CountryId = 68,Name = "Estonia", Code = "EE" },
        new Country { CountryId = 69,Name = "Ethiopia", Code = "ET" },
        new Country { CountryId = 70,Name = "Falkland Islands (Malvinas)", Code = "FK" },
        new Country { CountryId = 71,Name = "Faroe Islands", Code = "FO" },
        new Country { CountryId = 72,Name = "Fiji", Code = "FJ" },
        new Country { CountryId = 73,Name = "Finland", Code = "FI" },
        new Country { CountryId = 74,Name = "France", Code = "FR" },
        new Country { CountryId = 75,Name = "French Guiana", Code = "GF" },
        new Country { CountryId = 76,Name = "French Polynesia", Code = "PF" },
        new Country { CountryId = 77,Name = "French Southern Territories", Code = "TF" },
        new Country { CountryId = 78,Name = "Gabon", Code = "GA" },
        new Country { CountryId = 79,Name = "Gambia", Code = "GM" },
        new Country { CountryId = 80,Name = "Georgia", Code = "GE" },
        new Country { CountryId = 81,Name = "Germany", Code = "DE" },
        new Country { CountryId = 82,Name = "Ghana", Code = "GH" },
        new Country { CountryId = 83,Name = "Gibraltar", Code = "GI" },
        new Country { CountryId = 84,Name = "Greece", Code = "GR" },
        new Country { CountryId = 85,Name = "Greenland", Code = "GL" },
        new Country { CountryId = 86,Name = "Grenada", Code = "GD" },
        new Country { CountryId = 87,Name = "Guadeloupe", Code = "GP" },
        new Country { CountryId = 88,Name = "Guam", Code = "GU" },
        new Country { CountryId = 89,Name = "Guatemala", Code = "GT" },
        new Country { CountryId = 90,Name = "Guernsey", Code = "GG" },
        new Country { CountryId = 91,Name = "Guinea", Code = "GN" },
        new Country { CountryId = 92,Name = "Guinea-Bissau", Code = "GW" },
        new Country { CountryId = 93,Name = "Guyana", Code = "GY" },
        new Country { CountryId = 94,Name = "Haiti", Code = "HT" },
        new Country { CountryId = 95,Name = "Heard Island and Mcdonald Islands", Code = "HM" },
        new Country { CountryId = 96,Name = "Holy See (Vatican City State)", Code = "VA" },
        new Country { CountryId = 97,Name = "Honduras", Code = "HN" },
        new Country { CountryId = 98,Name = "Hong Kong", Code = "HK" },
        new Country { CountryId = 99,Name = "Hungary", Code = "HU" },
        new Country { CountryId = 100,Name = "Iceland", Code = "IS" },
        new Country { CountryId = 101,Name = "India", Code = "IN" },
        new Country { CountryId = 102,Name = "Indonesia", Code = "ID" },
        new Country { CountryId = 103,Name = "Iran, Islamic Republic Of", Code = "IR" },
        new Country { CountryId = 104,Name = "Iraq", Code = "IQ" },
        new Country { CountryId = 105,Name = "Ireland", Code = "IE" },
        new Country { CountryId = 106,Name = "Isle of Man", Code = "IM" },
        new Country { CountryId = 107,Name = "Israel", Code = "IL" },
        new Country { CountryId = 108,Name = "Italy", Code = "IT" },
        new Country { CountryId = 109,Name = "Jamaica", Code = "JM" },
        new Country { CountryId = 110,Name = "Japan", Code = "JP" },
        new Country { CountryId = 111,Name = "Jersey", Code = "JE" },
        new Country { CountryId = 112,Name = "Jordan", Code = "JO" },
        new Country { CountryId = 113,Name = "Kazakhstan", Code = "KZ" },
        new Country { CountryId = 114,Name = "Kenya", Code = "KE" },
        new Country { CountryId = 115,Name = "Kiribati", Code = "KI" },
        new Country { CountryId = 116,Name = "Korea, Democratic People'S Republic of", Code = "KP" },
        new Country { CountryId = 117,Name = "Korea, Republic of", Code = "KR" },
        new Country { CountryId = 118,Name = "Kuwait", Code = "KW" },
        new Country { CountryId = 119,Name = "Kyrgyzstan", Code = "KG" },
        new Country { CountryId = 120,Name = "Lao People'S Democratic Republic", Code = "LA" },
        new Country { CountryId = 121,Name = "Latvia", Code = "LV" },
        new Country { CountryId = 122,Name = "Lebanon", Code = "LB" },
        new Country { CountryId = 123,Name = "Lesotho", Code = "LS" },
        new Country { CountryId = 124,Name = "Liberia", Code = "LR" },
        new Country { CountryId = 125,Name = "Libyan Arab Jamahiriya", Code = "LY" },
        new Country { CountryId = 126,Name = "Liechtenstein", Code = "LI" },
        new Country { CountryId = 127,Name = "Lithuania", Code = "LT" },
        new Country { CountryId = 128,Name = "Luxembourg", Code = "LU" },
        new Country { CountryId = 129,Name = "Macao", Code = "MO" },
        new Country { CountryId = 130,Name = "Macedonia, The Former Yugoslav Republic of", Code = "MK" },
        new Country { CountryId = 131,Name = "Madagascar", Code = "MG" },
        new Country { CountryId = 132,Name = "Malawi", Code = "MW" },
        new Country { CountryId = 133,Name = "Malaysia", Code = "MY" },
        new Country { CountryId = 134,Name = "Maldives", Code = "MV" },
        new Country { CountryId = 135,Name = "Mali", Code = "ML" },
        new Country { CountryId = 136,Name = "Malta", Code = "MT" },
        new Country { CountryId = 137,Name = "Marshall Islands", Code = "MH" },
        new Country { CountryId = 138,Name = "Martinique", Code = "MQ" },
        new Country { CountryId = 139,Name = "Mauritania", Code = "MR" },
        new Country { CountryId = 140,Name = "Mauritius", Code = "MU" },
        new Country { CountryId = 141,Name = "Mayotte", Code = "YT" },
        new Country { CountryId = 142,Name = "Mexico", Code = "MX" },
        new Country { CountryId = 143,Name = "Micronesia, Federated States of", Code = "FM" },
        new Country { CountryId = 144,Name = "Moldova, Republic of", Code = "MD" },
        new Country { CountryId = 145,Name = "Monaco", Code = "MC" },
        new Country { CountryId = 146,Name = "Mongolia", Code = "MN" },
        new Country { CountryId = 147,Name = "Montenegro", Code = "ME" },
        new Country { CountryId = 148,Name = "Montserrat", Code = "MS" },
        new Country { CountryId = 149,Name = "Morocco", Code = "MA" },
        new Country { CountryId = 150,Name = "Mozambique", Code = "MZ" },
        new Country { CountryId = 151,Name = "Myanmar", Code = "MM" },
        new Country { CountryId = 152,Name = "Namibia", Code = "NA" },
        new Country { CountryId = 153,Name = "Nauru", Code = "NR" },
        new Country { CountryId = 154,Name = "Nepal", Code = "NP" },
        new Country { CountryId = 155,Name = "Netherlands", Code = "NL" },
        new Country { CountryId = 156,Name = "Netherlands Antilles", Code = "AN" },
        new Country { CountryId = 157,Name = "New Caledonia", Code = "NC" },
        new Country { CountryId = 158,Name = "New Zealand", Code = "NZ" },
        new Country { CountryId = 159,Name = "Nicaragua", Code = "NI" },
        new Country { CountryId = 160,Name = "Niger", Code = "NE" },
        new Country { CountryId = 161,Name = "Nigeria", Code = "NG" },
        new Country { CountryId = 162,Name = "Niue", Code = "NU" },
        new Country { CountryId = 163,Name = "Norfolk Island", Code = "NF" },
        new Country { CountryId = 164,Name = "Northern Mariana Islands", Code = "MP" },
        new Country { CountryId = 165,Name = "Norway", Code = "NO" },
        new Country { CountryId = 166,Name = "Oman", Code = "OM" },
        new Country { CountryId = 167,Name = "Pakistan", Code = "PK" },
        new Country { CountryId = 168,Name = "Palau", Code = "PW" },
        new Country { CountryId = 169,Name = "Palestinian Territory, Occupied", Code = "PS" },
        new Country { CountryId = 170,Name = "Panama", Code = "PA" },
        new Country { CountryId = 171,Name = "Papua New Guinea", Code = "PG" },
        new Country { CountryId = 172,Name = "Paraguay", Code = "PY" },
        new Country { CountryId = 173,Name = "Peru", Code = "PE" },
        new Country { CountryId = 174,Name = "Philippines", Code = "PH" },
        new Country { CountryId = 175,Name = "Pitcairn", Code = "PN" },
        new Country { CountryId = 176,Name = "Poland", Code = "PL" },
        new Country { CountryId = 177,Name = "Portugal", Code = "PT" },
        new Country { CountryId = 178,Name = "Puerto Rico", Code = "PR" },
        new Country { CountryId = 179,Name = "Qatar", Code = "QA" },
        new Country { CountryId = 180,Name = "Reunion", Code = "RE" },
        new Country { CountryId = 181,Name = "Romania", Code = "RO" },
        new Country { CountryId = 182,Name = "Russian Federation", Code = "RU" },
        new Country { CountryId = 183,Name = "RWANDA", Code = "RW" },
        new Country { CountryId = 184,Name = "Saint Helena", Code = "SH" },
        new Country { CountryId = 185,Name = "Saint Kitts and Nevis", Code = "KN" },
        new Country { CountryId = 186,Name = "Saint Lucia", Code = "LC" },
        new Country { CountryId = 187,Name = "Saint Pierre and Miquelon", Code = "PM" },
        new Country { CountryId = 188,Name = "Saint Vincent and the Grenadines", Code = "VC" },
        new Country { CountryId = 189,Name = "Samoa", Code = "WS" },
        new Country { CountryId = 190,Name = "San Marino", Code = "SM" },
        new Country { CountryId = 191,Name = "Sao Tome and Principe", Code = "ST" },
        new Country { CountryId = 192,Name = "Saudi Arabia", Code = "SA" },
        new Country { CountryId = 193,Name = "Senegal", Code = "SN" },
        new Country { CountryId = 194,Name = "Serbia", Code = "RS" },
        new Country { CountryId = 195,Name = "Seychelles", Code = "SC" },
        new Country { CountryId = 196,Name = "Sierra Leone", Code = "SL" },
        new Country { CountryId = 197,Name = "Singapore", Code = "SG" },
        new Country { CountryId = 198,Name = "Slovakia", Code = "SK" },
        new Country { CountryId = 199,Name = "Slovenia", Code = "SI" },
        new Country { CountryId = 200,Name = "Solomon Islands", Code = "SB" },
        new Country { CountryId = 201,Name = "Somalia", Code = "SO" },
        new Country { CountryId = 202,Name = "South Africa", Code = "ZA" },
        new Country { CountryId = 203,Name = "South Georgia and the South Sandwich Islands", Code = "GS" },
        new Country { CountryId = 204,Name = "Spain", Code = "ES" },
        new Country { CountryId = 205,Name = "Sri Lanka", Code = "LK" },
        new Country { CountryId = 206,Name = "Sudan", Code = "SD" },
        new Country { CountryId = 207,Name = "Suriname", Code = "SR" },
        new Country { CountryId = 208,Name = "Svalbard and Jan Mayen", Code = "SJ" },
        new Country { CountryId = 209,Name = "Swaziland", Code = "SZ" },
        new Country { CountryId = 210,Name = "Sweden", Code = "SE" },
        new Country { CountryId = 211,Name = "Switzerland", Code = "CH" },
        new Country { CountryId = 212,Name = "Syrian Arab Republic", Code = "SY" },
        new Country { CountryId = 213,Name = "Taiwan, Province of China", Code = "TW" },
        new Country { CountryId = 214,Name = "Tajikistan", Code = "TJ" },
        new Country { CountryId = 215,Name = "Tanzania, United Republic of", Code = "TZ" },
        new Country { CountryId = 216,Name = "Thailand", Code = "TH" },
        new Country { CountryId = 217,Name = "Timor-Leste", Code = "TL" },
        new Country { CountryId = 218,Name = "Togo", Code = "TG" },
        new Country { CountryId = 219,Name = "Tokelau", Code = "TK" },
        new Country { CountryId = 220,Name = "Tonga", Code = "TO" },
        new Country { CountryId = 221,Name = "Trinidad and Tobago", Code = "TT" },
        new Country { CountryId = 222,Name = "Tunisia", Code = "TN" },
        new Country { CountryId = 223,Name = "Turkey", Code = "TR" },
        new Country { CountryId = 224,Name = "Turkmenistan", Code = "TM" },
        new Country { CountryId = 225,Name = "Turks and Caicos Islands", Code = "TC" },
        new Country { CountryId = 226,Name = "Tuvalu", Code = "TV" },
        new Country { CountryId = 227,Name = "Uganda", Code = "UG" },
        new Country { CountryId = 228,Name = "Ukraine", Code = "UA" },
        new Country { CountryId = 229,Name = "United Arab Emirates", Code = "AE" },
        new Country { CountryId = 230,Name = "United Kingdom", Code = "GB" },
        new Country { CountryId = 231,Name = "United States", Code = "US" },
        new Country { CountryId = 232,Name = "United States Minor Outlying Islands", Code = "UM" },
        new Country { CountryId = 233,Name = "Uruguay", Code = "UY" },
        new Country { CountryId = 234,Name = "Uzbekistan", Code = "UZ" },
        new Country { CountryId = 235,Name = "Vanuatu", Code = "VU" },
        new Country { CountryId = 236,Name = "Venezuela", Code = "VE" },
        new Country { CountryId = 237,Name = "Viet Nam", Code = "VN" },
        new Country { CountryId = 238,Name = "Virgin Islands, British", Code = "VG" },
        new Country { CountryId = 239,Name = "Virgin Islands, U.S.", Code = "VI" },
        new Country { CountryId = 240,Name = "Wallis and Futuna", Code = "WF" },
        new Country { CountryId = 241,Name = "Western Sahara", Code = "EH" },
        new Country { CountryId = 242,Name = "Yemen", Code = "YE" },
        new Country { CountryId = 243,Name = "Zambia", Code = "ZM" },
        new Country { CountryId = 244,Name = "Zimbabwe", Code = "ZW" }
    };
}