// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ntmng.DataService;

#nullable disable

namespace Ntmng.DataService.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20221114141020_2022-11-14_1")]
    partial class _202211141
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ntmng.Model.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 2,
                            Code = "AX",
                            Name = "land Islands"
                        },
                        new
                        {
                            CountryId = 3,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            CountryId = 4,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            CountryId = 5,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            CountryId = 6,
                            Code = "AD",
                            Name = "AndorrA"
                        },
                        new
                        {
                            CountryId = 7,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            CountryId = 8,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            CountryId = 9,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            CountryId = 10,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = 11,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = 12,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            CountryId = 13,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            CountryId = 14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            CountryId = 15,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            CountryId = 16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 17,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            CountryId = 18,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            CountryId = 19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 20,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            CountryId = 21,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            CountryId = 22,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 23,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = 24,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            CountryId = 25,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            CountryId = 26,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            CountryId = 27,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            CountryId = 28,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = 29,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            CountryId = 30,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            CountryId = 31,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryId = 32,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryId = 33,
                            Code = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            CountryId = 34,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 35,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = 36,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            CountryId = 37,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            CountryId = 38,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            CountryId = 39,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = 40,
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            CountryId = 41,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            CountryId = 42,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            CountryId = 43,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            CountryId = 44,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = 45,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 46,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            CountryId = 47,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryId = 48,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = 49,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            CountryId = 50,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            CountryId = 51,
                            Code = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            CountryId = 52,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            CountryId = 53,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = 54,
                            Code = "CI",
                            Name = "Cote D'Ivoire"
                        },
                        new
                        {
                            CountryId = 55,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryId = 56,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            CountryId = 57,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryId = 58,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            CountryId = 59,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = 60,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            CountryId = 61,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            CountryId = 62,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = 63,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = 64,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryId = 65,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = 66,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = 67,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            CountryId = 68,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            CountryId = 69,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 70,
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            CountryId = 71,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            CountryId = 72,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            CountryId = 73,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            CountryId = 74,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 75,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            CountryId = 76,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            CountryId = 77,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            CountryId = 78,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            CountryId = 79,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            CountryId = 80,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryId = 81,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 82,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            CountryId = 83,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            CountryId = 84,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = 85,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            CountryId = 86,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            CountryId = 87,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            CountryId = 88,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            CountryId = 89,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = 90,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            CountryId = 91,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            CountryId = 92,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = 93,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            CountryId = 94,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            CountryId = 95,
                            Code = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            CountryId = 96,
                            Code = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            CountryId = 97,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = 98,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            CountryId = 99,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            CountryId = 100,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            CountryId = 101,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 102,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            CountryId = 103,
                            Code = "IR",
                            Name = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            CountryId = 104,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            CountryId = 105,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            CountryId = 106,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            CountryId = 107,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            CountryId = 108,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = 109,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryId = 110,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 111,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            CountryId = 112,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryId = 113,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 114,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            CountryId = 115,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryId = 116,
                            Code = "KP",
                            Name = "Korea, Democratic People'S Republic of"
                        },
                        new
                        {
                            CountryId = 117,
                            Code = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            CountryId = 118,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            CountryId = 119,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 120,
                            Code = "LA",
                            Name = "Lao People'S Democratic Republic"
                        },
                        new
                        {
                            CountryId = 121,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            CountryId = 122,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            CountryId = 123,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            CountryId = 124,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            CountryId = 125,
                            Code = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            CountryId = 126,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 127,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            CountryId = 128,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 129,
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            CountryId = 130,
                            Code = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            CountryId = 131,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            CountryId = 132,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            CountryId = 133,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryId = 134,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            CountryId = 135,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            CountryId = 136,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            CountryId = 137,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = 138,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            CountryId = 139,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            CountryId = 140,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            CountryId = 141,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            CountryId = 142,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryId = 143,
                            Code = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            CountryId = 144,
                            Code = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            CountryId = 145,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            CountryId = 146,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            CountryId = 147,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryId = 148,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            CountryId = 149,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            CountryId = 150,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            CountryId = 151,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            CountryId = 152,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            CountryId = 153,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            CountryId = 154,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            CountryId = 155,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 156,
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            CountryId = 157,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            CountryId = 158,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            CountryId = 159,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 160,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            CountryId = 161,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            CountryId = 162,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            CountryId = 163,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            CountryId = 164,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryId = 165,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            CountryId = 166,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            CountryId = 167,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryId = 168,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            CountryId = 169,
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            CountryId = 170,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            CountryId = 171,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = 172,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = 173,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            CountryId = 174,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            CountryId = 175,
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            CountryId = 176,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            CountryId = 177,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = 178,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            CountryId = 179,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            CountryId = 180,
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            CountryId = 181,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = 182,
                            Code = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            CountryId = 183,
                            Code = "RW",
                            Name = "RWANDA"
                        },
                        new
                        {
                            CountryId = 184,
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            CountryId = 185,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = 186,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = 187,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryId = 188,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = 189,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            CountryId = 190,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            CountryId = 191,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryId = 192,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 193,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            CountryId = 194,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            CountryId = 195,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            CountryId = 196,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = 197,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            CountryId = 198,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryId = 199,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            CountryId = 200,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = 201,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            CountryId = 202,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            CountryId = 203,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryId = 204,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 205,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = 206,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            CountryId = 207,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            CountryId = 208,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryId = 209,
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            CountryId = 210,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = 211,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            CountryId = 212,
                            Code = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            CountryId = 213,
                            Code = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            CountryId = 214,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 215,
                            Code = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            CountryId = 216,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryId = 217,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = 218,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            CountryId = 219,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            CountryId = 220,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            CountryId = 221,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = 222,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            CountryId = 223,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryId = 224,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 225,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryId = 226,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 227,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            CountryId = 228,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryId = 229,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 230,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 231,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            CountryId = 232,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryId = 233,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = 234,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 235,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 236,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = 237,
                            Code = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            CountryId = 238,
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            CountryId = 239,
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            CountryId = 240,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryId = 241,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            CountryId = 242,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            CountryId = 243,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            CountryId = 244,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Ntmng.Model.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LocalizationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.HasIndex("LocalizationId");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Ntmng.Model.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Ntmng.Model.Models.Localization", b =>
                {
                    b.Property<int>("LocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizationId"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LocalizationId");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Localizations");

                    b.HasData(
                        new
                        {
                            LocalizationId = 1,
                            DateAdded = new DateTime(2022, 11, 14, 15, 10, 20, 381, DateTimeKind.Local).AddTicks(488),
                            Description = "Default localization.",
                            IsActive = true,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("Ntmng.Model.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ModuleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            ModuleId = 1,
                            Description = "Network ping monitoring.",
                            IsActive = true,
                            Name = "Ping Monitor"
                        });
                });

            modelBuilder.Entity("Ntmng.Model.Models.ModuleData", b =>
                {
                    b.Property<int>("ModuleDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleDataId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ResponseResult")
                        .HasColumnType("bit");

                    b.Property<int?>("ResponseTime")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ModuleDataId");

                    b.HasIndex("UserId");

                    b.ToTable("ModulesData");
                });

            modelBuilder.Entity("Ntmng.Model.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Ntmng.Model.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("CountryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateAdded = new DateTime(2022, 11, 14, 15, 10, 20, 381, DateTimeKind.Local).AddTicks(407),
                            Email = "kwojcieszek@gmail.com",
                            FirstName = "Kamil",
                            IsActive = false,
                            IsEmailConfirmed = false,
                            LastName = "Wojcieszek",
                            MobilePhone = "602174021",
                            Name = "Kamil Wojcieszek",
                            Password = "HiP+DbplZA8yEB+dW3tQDw9yoGPtzZymRY8u94L8BOE=",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Ntmng.Model.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Ntmng.Model.Models.Device", b =>
                {
                    b.HasOne("Ntmng.Model.Models.Localization", "Localization")
                        .WithMany()
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ntmng.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ntmng.Model.Models.Localization", b =>
                {
                    b.HasOne("Ntmng.Model.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Ntmng.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ntmng.Model.Models.ModuleData", b =>
                {
                    b.HasOne("Ntmng.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ntmng.Model.Models.User", b =>
                {
                    b.HasOne("Ntmng.Model.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Ntmng.Model.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.Navigation("Country");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ntmng.Model.Models.UserRole", b =>
                {
                    b.HasOne("Ntmng.Model.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ntmng.Model.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
